version: '3.8'
volumes:
  local-sql-data:
services:
  local-mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    ports:
      - 1433:1433
    volumes:
      - local-sql-data:/var/opt/mssql