trigger:
  - master

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net7.0'
  dotNetVersion: '7.0.x'
  targetRuntime: 'win-x64'

pool:
  vmImage: windows-latest

steps:
  - template: build-WEB.yml
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/TaHooK.Web.App.csproj'
      arguments: '--configuration $(BuildConfiguration) --framework $(dotNetFramework) --runtime $(targetRuntime) --output $(Build.ArtifactStagingDirectory)/web'
      modifyOutputPath: false

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/web'
      ArtifactName: 'WEB'
      publishLocation: 'Container'